-- Pubgolf web schema
-- Fresh Supabase project migration. Run once in SQL Editor or through Supabase CLI.

create extension if not exists pgcrypto;

create type public.game_status as enum ('lobby', 'active', 'finished');
create type public.wheel_mode as enum ('classic', 'everyone', 'random');
create type public.challenge_duration as enum ('instant', 'whole_pub', 'until_next_pub');
create type public.assignment_status as enum ('assigned', 'completed', 'failed');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (char_length(username) between 2 and 30),
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles(id, username)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'username', ''), 'player-' || left(new.id::text, 6))
  );
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create table public.bars (
  id bigint generated by default as identity primary key,
  name text not null,
  city text not null,
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default now()
);

create table public.drinks (
  id bigint generated by default as identity primary key,
  bar_id bigint not null references public.bars(id) on delete cascade,
  name text not null,
  size_ml integer,
  price numeric(8,2),
  par smallint not null default 4 check (par between 1 and 20),
  type text
);

create table public.games (
  id bigint generated by default as identity primary key,
  code text not null unique default upper(substr(encode(gen_random_bytes(4), 'hex'), 1, 6)),
  host_id uuid not null references public.profiles(id),
  status public.game_status not null default 'lobby',
  holes smallint not null check (holes between 1 and 18),
  current_hole smallint not null default 1,
  wheel_count smallint not null default 0,
  wheel_mode public.wheel_mode not null default 'classic',
  random_min smallint not null default 1,
  random_max smallint not null default 3,
  created_at timestamptz not null default now(),
  check (wheel_count between 0 and holes),
  check (random_min >= 1 and random_max >= random_min)
);

create table public.game_players (
  game_id bigint not null references public.games(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  active boolean not null default true,
  primary key (game_id, user_id)
);

create table public.game_holes (
  game_id bigint not null references public.games(id) on delete cascade,
  hole_number smallint not null,
  bar_id bigint not null references public.bars(id),
  wheel_enabled boolean not null default false,
  primary key (game_id, hole_number)
);

create table public.results (
  game_id bigint not null references public.games(id) on delete cascade,
  hole_number smallint not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  score smallint not null default 0,
  confirmed boolean not null default false,
  created_at timestamptz not null default now(),
  primary key (game_id, hole_number, user_id)
);

create table public.wheel_challenges (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  emoji text not null,
  title text not null,
  description text not null,
  success_delta smallint not null default 0,
  fail_delta smallint not null default 0,
  duration public.challenge_duration not null default 'whole_pub',
  active boolean not null default true
);

create table public.wheel_assignments (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games(id) on delete cascade,
  hole_number smallint not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  challenge_id bigint not null references public.wheel_challenges(id),
  status public.assignment_status not null default 'assigned',
  score_delta smallint not null default 0,
  assigned_at timestamptz not null default now(),
  revealed_at timestamptz,
  resolved_at timestamptz,
  unique (game_id, hole_number, user_id)
);

insert into public.wheel_challenges (slug, emoji, title, description, success_delta, fail_delta, duration) values
('chug', '🍺', 'Chug', 'Klara utmaningen enligt gruppens regler.', -2, 2, 'instant'),
('swap', '🔁', 'Swap', 'Du får vid valfritt tillfälle byta drink med någon annan.', 0, 0, 'whole_pub'),
('sing', '🎤', 'Sing', 'Sjung något för gruppen.', -2, 2, 'instant'),
('shot', '🔥', 'Shot', 'Genomför challenge:n enligt gruppens regler.', -2, 2, 'instant'),
('story', '😳', 'Story', 'Berätta en story som gruppen godkänner.', -2, 2, 'instant'),
('accent', '🇬🇧', 'Accent', 'Prata med accent tills nästa bar.', -2, 2, 'until_next_pub'),
('buddy', '👫', 'Buddy', 'Välj en drinking buddy för den här baren.', 0, 0, 'whole_pub'),
('dance', '💃', 'Dance', 'Dansa för gruppen.', -2, 2, 'instant');

-- Helper functions used by RLS. SECURITY DEFINER avoids recursive game_players policies.
create or replace function public.is_game_player(p_game_id bigint, p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.game_players gp
    where gp.game_id = p_game_id and gp.user_id = p_user_id and gp.active
  );
$$;

create or replace function public.is_game_host(p_game_id bigint, p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.games g where g.id = p_game_id and g.host_id = p_user_id
  );
$$;

alter table public.profiles enable row level security;
alter table public.bars enable row level security;
alter table public.drinks enable row level security;
alter table public.games enable row level security;
alter table public.game_players enable row level security;
alter table public.game_holes enable row level security;
alter table public.results enable row level security;
alter table public.wheel_challenges enable row level security;
alter table public.wheel_assignments enable row level security;

create policy "profiles readable by authenticated" on public.profiles for select to authenticated using (true);
create policy "own profile update" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy "bars readable" on public.bars for select to authenticated using (true);
create policy "drinks readable" on public.drinks for select to authenticated using (true);
create policy "challenges readable" on public.wheel_challenges for select to authenticated using (active);

create policy "players read their games" on public.games for select to authenticated using (public.is_game_player(id) or host_id = auth.uid());
create policy "host can update game" on public.games for update to authenticated using (host_id = auth.uid()) with check (host_id = auth.uid());
create policy "players read player list" on public.game_players for select to authenticated using (public.is_game_player(game_id));
create policy "users can join as themselves" on public.game_players for insert to authenticated with check (user_id = auth.uid());
create policy "players read holes" on public.game_holes for select to authenticated using (public.is_game_player(game_id));
create policy "players read results" on public.results for select to authenticated using (public.is_game_player(game_id));
create policy "players insert own results" on public.results for insert to authenticated with check (public.is_game_player(game_id) and user_id = auth.uid());
create policy "players update own results" on public.results for update to authenticated using (public.is_game_player(game_id) and user_id = auth.uid()) with check (user_id = auth.uid());
create policy "players read revealed assignments" on public.wheel_assignments for select to authenticated
using (public.is_game_player(game_id) and revealed_at is not null);

create or replace view public.game_player_list
with (security_invoker = true)
as
select gp.game_id, gp.user_id, p.username, gp.joined_at
from public.game_players gp
join public.profiles p on p.id = gp.user_id
where gp.active;

-- Atomic game creation. The selected Wheel holes are decided server-side once.
create or replace function public.create_game(
  p_bar_ids bigint[],
  p_wheel_count integer default 0,
  p_wheel_mode public.wheel_mode default 'classic',
  p_random_min integer default 1,
  p_random_max integer default 3
)
returns table(game_id bigint, code text)
language plpgsql
security definer set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_game public.games%rowtype;
  v_holes integer := coalesce(array_length(p_bar_ids, 1), 0);
begin
  if v_user is null then raise exception 'Not authenticated'; end if;
  if v_holes < 1 or v_holes > 18 then raise exception 'Choose between 1 and 18 bars'; end if;
  if p_wheel_count < 0 or p_wheel_count > v_holes then raise exception 'Invalid Wheel count'; end if;
  if p_random_min < 1 or p_random_max < p_random_min then raise exception 'Invalid random range'; end if;
  if exists (select 1 from unnest(p_bar_ids) x left join public.bars b on b.id=x where b.id is null) then
    raise exception 'One or more bars do not exist';
  end if;

  insert into public.games(host_id, holes, wheel_count, wheel_mode, random_min, random_max)
  values (v_user, v_holes, p_wheel_count, p_wheel_mode, p_random_min, p_random_max)
  returning * into v_game;

  insert into public.game_players(game_id, user_id) values (v_game.id, v_user);

  with wheel_holes as (
    select n from generate_series(1, v_holes) n order by random() limit p_wheel_count
  )
  insert into public.game_holes(game_id, hole_number, bar_id, wheel_enabled)
  select v_game.id, ordinality::smallint, bar_id,
         exists(select 1 from wheel_holes wh where wh.n = ordinality)
  from unnest(p_bar_ids) with ordinality as selected(bar_id, ordinality);

  return query select v_game.id, v_game.code;
end;
$$;

-- Join by 6-character code.
create or replace function public.join_game(p_code text)
returns bigint
language plpgsql
security definer set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_game_id bigint;
begin
  if v_user is null then raise exception 'Not authenticated'; end if;
  select id into v_game_id from public.games where code = upper(trim(p_code)) and status <> 'finished';
  if v_game_id is null then raise exception 'Game not found'; end if;
  insert into public.game_players(game_id, user_id) values (v_game_id, v_user) on conflict do nothing;
  return v_game_id;
end;
$$;

-- Generates all assignments exactly once for the hole, but only returns the caller's assignment.
create or replace function public.assign_wheel_for_hole(p_game_id bigint, p_hole_number integer)
returns setof public.wheel_assignments
language plpgsql
security definer set search_path = public
as $$
declare
  v_mode public.wheel_mode;
  v_min integer;
  v_max integer;
  v_players integer;
  v_target integer;
  v_challenges integer;
begin
  if not public.is_game_player(p_game_id) then raise exception 'Not a player in this game'; end if;
  if not exists (select 1 from public.game_holes where game_id=p_game_id and hole_number=p_hole_number and wheel_enabled) then
    raise exception 'No Wheel of Doom on this hole';
  end if;

  perform pg_advisory_xact_lock((p_game_id % 2147483647)::integer, p_hole_number);

  if not exists (select 1 from public.wheel_assignments where game_id=p_game_id and hole_number=p_hole_number) then
    select wheel_mode, random_min, random_max into v_mode, v_min, v_max from public.games where id=p_game_id;
    select count(*) into v_players from public.game_players where game_id=p_game_id and active;
    select count(*) into v_challenges from public.wheel_challenges where active;
    if v_players = 0 or v_challenges = 0 then raise exception 'No players or challenges available'; end if;

    if v_mode = 'classic' then
      v_target := 1;
    elsif v_mode = 'everyone' then
      v_target := v_players;
    else
      v_min := least(greatest(v_min, 1), v_players);
      v_max := least(greatest(v_max, v_min), v_players);
      v_target := floor(random() * (v_max - v_min + 1))::integer + v_min;
    end if;

    with selected_players as (
      select user_id, row_number() over () as rn
      from (
        select user_id from public.game_players
        where game_id=p_game_id and active
        order by random()
        limit v_target
      ) p
    ), shuffled_challenges as (
      select id, row_number() over () as rn
      from (
        select id from public.wheel_challenges where active order by random()
      ) c
    )
    insert into public.wheel_assignments(game_id, hole_number, user_id, challenge_id)
    select p_game_id, p_hole_number, sp.user_id, sc.id
    from selected_players sp
    join shuffled_challenges sc on sc.rn = ((sp.rn - 1) % v_challenges) + 1;
  end if;

  return query
  select wa.* from public.wheel_assignments wa
  where wa.game_id=p_game_id and wa.hole_number=p_hole_number and wa.user_id=auth.uid();
end;
$$;

-- The challenge is only returned when the user actually presses Spin.
create or replace function public.reveal_my_wheel_assignment(p_game_id bigint, p_hole_number integer)
returns table(
  assignment_id bigint,
  id bigint,
  emoji text,
  title text,
  description text,
  success_delta smallint,
  fail_delta smallint
)
language plpgsql
security definer set search_path = public
as $$
begin
  perform * from public.assign_wheel_for_hole(p_game_id, p_hole_number);

  update public.wheel_assignments
  set revealed_at = coalesce(revealed_at, now())
  where game_id=p_game_id and hole_number=p_hole_number and user_id=auth.uid();

  return query
  select wa.id, wc.id, wc.emoji, wc.title, wc.description, wc.success_delta, wc.fail_delta
  from public.wheel_assignments wa
  join public.wheel_challenges wc on wc.id=wa.challenge_id
  where wa.game_id=p_game_id and wa.hole_number=p_hole_number and wa.user_id=auth.uid();
end;
$$;

create or replace function public.resolve_my_wheel_assignment(p_game_id bigint, p_hole_number integer, p_completed boolean)
returns smallint
language plpgsql
security definer set search_path = public
as $$
declare
  v_delta smallint;
begin
  if not public.is_game_player(p_game_id) then raise exception 'Not a player in this game'; end if;

  select case when p_completed then wc.success_delta else wc.fail_delta end
  into v_delta
  from public.wheel_assignments wa
  join public.wheel_challenges wc on wc.id=wa.challenge_id
  where wa.game_id=p_game_id and wa.hole_number=p_hole_number and wa.user_id=auth.uid();

  if v_delta is null then raise exception 'No Wheel assignment found'; end if;

  update public.wheel_assignments
  set status = case when p_completed then 'completed'::public.assignment_status else 'failed'::public.assignment_status end,
      score_delta = v_delta,
      resolved_at = now()
  where game_id=p_game_id and hole_number=p_hole_number and user_id=auth.uid();

  return v_delta;
end;
$$;

-- Leave a lobby/game as the current user. If the host leaves a lobby, the lobby is closed.
create or replace function public.leave_game(p_code text)
returns void
language plpgsql
security definer set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_game public.games%rowtype;
begin
  if v_user is null then raise exception 'Not authenticated'; end if;
  select * into v_game from public.games where code = upper(trim(p_code));
  if v_game.id is null then return; end if;

  if v_game.host_id = v_user and v_game.status = 'lobby' then
    delete from public.games where id = v_game.id;
  else
    delete from public.game_players where game_id = v_game.id and user_id = v_user;
  end if;
end;
$$;

grant execute on function public.create_game(bigint[], integer, public.wheel_mode, integer, integer) to authenticated;
grant execute on function public.join_game(text) to authenticated;
grant execute on function public.leave_game(text) to authenticated;
grant execute on function public.assign_wheel_for_hole(bigint, integer) to authenticated;
grant execute on function public.reveal_my_wheel_assignment(bigint, integer) to authenticated;
grant execute on function public.resolve_my_wheel_assignment(bigint, integer, boolean) to authenticated;

-- Initial Umeå bars, based on the bars referenced by the original mobile app.
insert into public.bars(name, city) values
('Megazone', 'Umeå'),
('Lion Bar', 'Umeå'),
('Kappa Bar', 'Umeå'),
('O''Learys', 'Umeå'),
('Orangeriet', 'Umeå'),
('Allstar', 'Umeå'),
('Harrys', 'Umeå'),
('Sjöbris', 'Umeå'),
('Lottas Krog & Pub', 'Umeå');
